- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/meta.yml
  minPlayers: 35
  maxPlayers: 70
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Meta {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs:
            # cmd
            Captain: [ 1, 1 ]
            BlueShieldOfficer: [ 1, 1 ]
            # law
            IAA: [ 1, 1 ]
            Lawyer: [ 2, 2 ]
            # sec
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            Detective: [ 1, 1 ]
            SecurityPilot: [ 1, 1 ]
            SecurityOfficer: [ 4, 4 ]
            Brigmedic: [ 1, 1 ]
            SecurityCadet: [ 2, 2 ]
            # med
            ChiefMedicalOfficer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            Chemist: [ 3, 3 ]
            MedicalDoctor: [ 4, 4 ]
            Paramedic: [ 1, 1 ]
            Coroner: [ 1, 1 ]
            MedicalIntern: [ 4, 4 ]
            # rnd
            ResearchDirector: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            Scientist: [ 4, 4 ]
            ResearchAssistant: [ 4, 4 ]
            # eng
            ChiefEngineer: [ 1, 1 ]
            SeniorEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 5 ]
            TechnicalAssistant: [ 4, 4 ]
            # sup
            Quartermaster: [ 1, 1 ]
            SeniorSalvageSpecialist: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            # civ
            HeadOfPersonnel: [ 1, 1 ]
            SeniorAdministrator: [ 1, 1 ]
            Chef: [ 2, 2 ]
            Botanist: [ 2, 2 ]
            Bartender: [ 2, 2 ]
            ServiceWorker: [ 2, 3 ]
            Janitor: [ 1, 2 ]
            Librarian: [ 1, 1 ]
            Chaplain: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Passenger: [ -1, -1 ]
            Mime: [ 1, 1 ]
            Clown: [ 1, 1 ]
            # sil
            StationAi: [ 1, 1 ]
            Borg: [ 2, 2 ]
            BorgSecurity: [ 1, 1 ]
            # etc
            ClownSponsor: [ 0, 2 ]
